<a href="https://colab.research.google.com/github/rebeca07-pedrozo/Python_ciencia_de_datos/blob/main/colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy pandas matplotlib

**Arrays en numpy**

In [1]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [ ]:
vector=np.array([1,2,3])
print(type(vector))
print(vector)

In [ ]:
matrix =np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

In [ ]:
array_arange=np.arange(10)
print(array_arange)

In [ ]:
eye_matrix=np.eye(6)
print(eye_matrix)

In [ ]:
diag= np.diag([1,2,3])
print(diag)

In [ ]:
random =np.random.random((2,4))
print(random)

In [ ]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.shape)
print(array.dtype)

In [ ]:
array = np.array([[1,2,3],[4,5,6]])
print(array.shape)

In [ ]:
z=np.array(8, dtype=np.uint8)
print(z)

In [ ]:
double_array=np.array([1,2,3], dtype=np.float64)
print(double_array)

In [ ]:
z=z.astype(np.float64)
print(z)

In [ ]:
array

In [ ]:
array=array.astype(np.float64)
print(array)

In [ ]:
array = np.array([[1,2,3],[4,5,6]])
add = np.sum(array)
print(add)

In [ ]:
array = np.array([[1,3,4],[7,9,0]])
sum = np.sum(array)
array = sum
print(sum)

In [ ]:
array = np.array([[1,3,4],[7,9,0]])
arrai = np.array([[7,9,0],[1,3,4]])
sum=np.sum(array+arrai)
array_total=sum
print(array_total)

In [ ]:
mean = np.mean(array)
print(mean)

In [ ]:
std=np.std(array)
print(std)

dot es multiplicar


# New Section

In [ ]:
import numpy as np
array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

In [ ]:
print(array[1:4])

In [ ]:
print(array[-1:-7])

In [ ]:
print(array[1:7])

In [ ]:
array = np.array([10,20,30,40,50])
bool_index = array>25
print(bool_index)

In [ ]:
print(array[2])

In [ ]:
index=[2,3,4]
print(array[index])

In [ ]:
array=np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,1])

In [ ]:
print(array[:2,:2])

In [ ]:
array=np.random.randint(1,100,size=(10,10))
print(array)

In [ ]:
print(array[5:8,5:7])

In [ ]:
prices=np.array([200,300,400])
discount=np.array([0.9])
prices_with_discount=prices*discount
print(prices_with_discount)

In [ ]:
prices=np.random.randint(100,500, size=(3,3))
discount=np.array([10,20,30])
prices_plus_discount=prices+discount
print(prices)
print(discount)
print(prices_plus_discount)

[[227 311 142]
 [101 254 269]
 [491 417 398]]
[10 20 30]
[[237 331 172]
 [111 274 299]
 [501 437 428]]


In [ ]:
array=np.array([1,2,3,4,5])
print(np.all(array>9))


False


In [ ]:
print(np.any(array>0))

True


In [ ]:
from typing import Concatenate
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
concatenate=np.concatenate([array_a,array_b])
print(concatenate)

[1 2 3 4 5 6]


In [ ]:
stecked_h=np.hstack((array_a,array_b))
print(stecked_h)

[1 2 3 4 5 6]


In [ ]:
array_c=np.arange(1,10)
split_array=np.split(array_c,3)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [3]:
array=np.random.randint(1,100, size=(4,4))
split_array=np.split(array,2)
print(array)
print(split_array)


[[21 51 22 79]
 [52 22 53 23]
 [ 3  5 13 30]
 [19 30 24 20]]
[array([[21, 51, 22, 79],
       [52, 22, 53, 23]]), array([[ 3,  5, 13, 30],
       [19, 30, 24, 20]])]


# Empresas

In [11]:
survey_responses=np.array(["bueno", "malo", "mas o menos", "aceptable",
                           "bueno", "malo", "mas o menos", "aceptable", "bueno",
                           "malo", "mas o menos", "aceptable", "bueno", "malo",
                           "mas o menos", "aceptable", "qa", "qa","qa"])
print(np.unique(survey_responses))

['aceptable' 'bueno' 'malo' 'mas o menos' 'qa']


In [12]:
unique_elements, counts=np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['aceptable' 'bueno' 'malo' 'mas o menos' 'qa']
[4 4 4 4 3]


In [16]:
array_x=np.arange(10)
view_y=array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [18]:
array_x=np.arange(10)
copy_x=array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]
