<a href="https://colab.research.google.com/github/rebeca07-pedrozo/Python_ciencia_de_datos/blob/main/colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install numpy pandas matplotlib

**Arrays en numpy**

In [7]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [8]:
vector=np.array([1,2,3])
print(type(vector))
print(vector)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
matrix =np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
array_arange=np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
eye_matrix=np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [13]:
diag= np.diag([1,2,3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [14]:
random =np.random.random((2,4))
print(random)

[[0.54693279 0.19390738 0.92408152 0.05521985]
 [0.47628141 0.41609017 0.92964403 0.20174222]]


In [15]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(3, 3)
int64


In [16]:
array = np.array([[1,2,3],[4,5,6]])
print(array.shape)

(2, 3)


In [17]:
z=np.array(8, dtype=np.uint8)
print(z)

8


In [18]:
double_array=np.array([1,2,3], dtype=np.float64)
print(double_array)

[1. 2. 3.]


In [19]:
z=z.astype(np.float64)
print(z)

8.0


In [20]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array=array.astype(np.float64)
print(array)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
array = np.array([[1,2,3],[4,5,6]])
add = np.sum(array)
print(add)

21


In [23]:
array = np.array([[1,3,4],[7,9,0]])
sum = np.sum(array)
array = sum
print(sum)

24


In [24]:
array = np.array([[1,3,4],[7,9,0]])
arrai = np.array([[7,9,0],[1,3,4]])
sum=np.sum(array+arrai)
array_total=sum
print(array_total)

48


In [25]:
mean = np.mean(array)
print(mean)

4.0


In [26]:
std=np.std(array)
print(std)

3.1622776601683795


dot es multiplicar


# New Section

In [27]:
import numpy as np
array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [28]:
print(array[1:4])

[20 30 40]


In [29]:
print(array[-1:-7])

[]


In [30]:
print(array[1:7])

[20 30 40 50]


In [31]:
array = np.array([10,20,30,40,50])
bool_index = array>25
print(bool_index)

[False False  True  True  True]


In [32]:
print(array[2])

30


In [33]:
index=[2,3,4]
print(array[index])

[30 40 50]


In [34]:
array=np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,1])

[[3 3 1]
 [5 7 5]
 [8 3 3]]
3


In [35]:
print(array[:2,:2])

[[3 3]
 [5 7]]


In [36]:
array=np.random.randint(1,100,size=(10,10))
print(array)

[[10 46 69 57 10 65 99 53 50 94]
 [44 34 87 32 50 81 10 58 38 52]
 [29 28 41 89  1 46 88 73 14 66]
 [31 47 89  9 37 71 59 12 40  7]
 [36 20  4 11 98 93  6 40 79 37]
 [72 95  7 56 70 86 39 45 49 17]
 [65 38 24 10 18  2 63 87 24 24]
 [82 42 60 66 76 29 33 68 85  3]
 [30 18 42 68 65 11 24 99 59 37]
 [39  9 36 37 16 99 95 58 11 17]]


In [37]:
print(array[5:8,5:7])

[[86 39]
 [ 2 63]
 [29 33]]


In [38]:
prices=np.array([200,300,400])
discount=np.array([0.9])
prices_with_discount=prices*discount
print(prices_with_discount)

[180. 270. 360.]


In [39]:
prices=np.random.randint(100,500, size=(3,3))
discount=np.array([10,20,30])
prices_plus_discount=prices+discount
print(prices)
print(discount)
print(prices_plus_discount)

[[206 207 217]
 [156 111 401]
 [211 190 221]]
[10 20 30]
[[216 227 247]
 [166 131 431]
 [221 210 251]]


In [40]:
array=np.array([1,2,3,4,5])
print(np.all(array>9))


False


In [41]:
print(np.any(array>0))

True


In [42]:
from typing import Concatenate
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
concatenate=np.concatenate([array_a,array_b])
print(concatenate)

[1 2 3 4 5 6]


In [43]:
stecked_h=np.hstack((array_a,array_b))
print(stecked_h)

[1 2 3 4 5 6]


In [44]:
array_c=np.arange(1,10)
split_array=np.split(array_c,3)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [45]:
array=np.random.randint(1,100, size=(4,4))
split_array=np.split(array,2)
print(array)
print(split_array)


[[25 57 89 43]
 [39 75 43 94]
 [93 44 77 11]
 [98 94 83 61]]
[array([[25, 57, 89, 43],
       [39, 75, 43, 94]]), array([[93, 44, 77, 11],
       [98, 94, 83, 61]])]


# Empresas

In [46]:
survey_responses=np.array(["bueno", "malo", "mas o menos", "aceptable",
                           "bueno", "malo", "mas o menos", "aceptable", "bueno",
                           "malo", "mas o menos", "aceptable", "bueno", "malo",
                           "mas o menos", "aceptable", "qa", "qa","qa"])
print(np.unique(survey_responses))

['aceptable' 'bueno' 'malo' 'mas o menos' 'qa']


In [47]:
unique_elements, counts=np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['aceptable' 'bueno' 'malo' 'mas o menos' 'qa']
[4 4 4 4 3]


In [48]:
array_x=np.arange(10)
view_y=array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [49]:
array_x=np.arange(10)
copy_x=array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


# A^t
Transposicion de matrices

In [50]:
matrix=np.array([[1,2,3], [4,5,6], [7,8,9]])
transposed_matrix=matrix.T
print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [51]:
array=np.arange(1,13)
reshaped_array=array.reshape(3,4)
print(array)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
reversed_array=array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [53]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
fattened_array=matrix.flatten()
print(matrix)
print(fattened_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# Calculos matriciales

In [68]:
A=np.array([[1,2],[3,4]])
B=np.array([[3,4],[7,8]])
dot = np.dot(A,B)
print (dot)

[[17 20]
 [37 44]]


In [70]:
A=np.array([[1,2],[3,4]])
det_A=np.linalg.det(A)
inversa= np.linalg.inv(A)
print(A)
print(det_A)
print (inversa)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


# Ejercicios

In [71]:
N=np.array([[1,2,3],[4,5,6],[7,8,9]])
R=np.array([[9,10,11], [13,24,15], [16,17,18]])
print(R)
print(N)

[[ 9 10 11]
 [13 24 15]
 [16 17 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
print(N+R)
print(R-N)
print(R/N)
print(N*R)

[[10 12 14]
 [17 29 21]
 [23 25 27]]
[[ 8  8  8]
 [ 9 19  9]
 [ 9  9  9]]
[[9.         5.         3.66666667]
 [3.25       4.8        2.5       ]
 [2.28571429 2.125      2.        ]]
[[  9  20  33]
 [ 52 120  90]
 [112 136 162]]


In [90]:
import numpy as np

N = np.array([[2, 1],
              [1, 3]])
b = np.array([9, 11])
x = np.linalg.solve(N, b)
print(x)

[3.2 2.6]


#Media, varianza, desviacion estandar

In [74]:
datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44444444444444
Mediana: 67.0
Varianza: 484.02469135802465
Desviación estándar: 22.000561160071


In [86]:
A=np.random.randint(1,10, size=(2,2))
E=np.random.randint(10,20, size=(2,2))
print(A)
print(E)

[[3 3]
 [9 5]]
[[13 11]
 [14 18]]


In [87]:
print(A+E)
print(A*E)
print(E-A)
print(np.linalg.inv(A))

[[16 14]
 [23 23]]
[[ 39  33]
 [126  90]]
[[10  8]
 [ 5 13]]
[[-0.41666667  0.25      ]
 [ 0.75       -0.25      ]]


In [95]:
A=np.random.randint(1,10, size=(2,2))
print (A)
b= np.array([3,5])
print(b)
x=np.linalg.solve(A,b)
print(x)

[[1 7]
 [6 6]]
[3 5]
[0.47222222 0.36111111]


array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1

In [97]:


datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: -0.017973013484880226
Desviación estándar de los datos simulados: 0.9831866247861485
