<a href="https://colab.research.google.com/github/rebeca07-pedrozo/Python_ciencia_de_datos/blob/main/Ventas_mensualesipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
month = np.array(['Enero', 'Febrero', 'Marzo', 'Abril',
                  'Mayo', 'Junio', 'Julio', 'Agosto',
                  'Septiembre', 'Octubre', 'Noviembre',
                  'Diciembre'])
product_A = np.array([150,200,250,300,220,210,180,190,230,240,280,300])
product_B = np.array([180,210,230,250,270,260,240,250,270,290,310,330])
product_c = np.array([200,220,240,260,280,300,320,340,360,380,400,420])

In [4]:
total_productoA= np.sum(product_A)
total_productoB= np.sum(product_B)
total_productoC= np.sum(product_c)
print(total_productoA)
print(total_productoB)
print(total_productoC)


2750
3090
3720


In [5]:
TresPrimerosMesesA=np.sum(product_A[:3])
TresPrimerosMesesB=np.sum(product_B[:3])
TresPrimerosMesesC=np.sum(product_c[:3])
primerosTresMeses=np.array([TresPrimerosMesesA,TresPrimerosMesesB,TresPrimerosMesesC])
print(primerosTresMeses)

[600 620 660]


In [6]:
Concatenar=np.concatenate((product_A,product_B,product_c))
print(Concatenar)

[150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


In [7]:
unique_elements, counts=np.unique(Concatenar, return_counts=True)
print(unique_elements)
print(counts)

[150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
 360 380 400 420]
[1 2 1 2 2 2 2 3 3 2 2 2 1 3 1 1 1 1 1 1 1 1]


In [8]:
counts=np.mean(counts)
print(counts)

1.6363636363636365


In [9]:
reshaped_array=product_A.reshape(6,2)
print(product_A)
print(reshaped_array)

[150 200 250 300 220 210 180 190 230 240 280 300]
[[150 200]
 [250 300]
 [220 210]
 [180 190]
 [230 240]
 [280 300]]


In [10]:
reshaped_array=product_A.reshape(6,2)
print(product_A)
print(reshaped_array)

[150 200 250 300 220 210 180 190 230 240 280 300]
[[150 200]
 [250 300]
 [220 210]
 [180 190]
 [230 240]
 [280 300]]


In [24]:
short = print(reshaped_array[:3])
long = print(reshaped_array[3:6])
total= print(reshaped_array[:6])
totall=(print(np.sum(reshaped_array)))

[[150 200]
 [250 300]
 [220 210]]
[[180 190]
 [230 240]
 [280 300]]
[[150 200]
 [250 300]
 [220 210]
 [180 190]
 [230 240]
 [280 300]]
2750
